import {
  Camera,
  Upload,
  Loader2 as Spinner,
  Copy,
  Twitter,
  Send as Telegram,
  Globe,
  Clock,
  Check,
  X,
  LayoutDashboard,
  Book as BookOpen,
  Users,
  Wallet as Wallet2,
  Settings,
  Users as Users2,
  LogOut,
  Eye,
  Play,
  CheckCircle,
  AlertCircle,
  Ban,
  Edit,
  Trash,
  Search,
  ChevronLeft,
  ChevronRight,
  Plus,
  type LucideIcon
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  camera: Camera,
  upload: Upload,
  spinner: Spinner,
  copy: Copy,
  twitter: Twitter,
  telegram: Telegram,
  globe: Globe,
  clock: Clock,
  check: Check,
  x: X,
  close: X,
  dashboard: LayoutDashboard,
  book: BookOpen,
  users: Users,
  wallet: Wallet2,
  settings: Settings,
  referrals: Users2,
  logout: LogOut,
  eye: Eye,
  play: Play,
  checkCircle: CheckCircle,
  alertCircle: AlertCircle,
  ban: Ban,
  edit: Edit,
  trash: Trash,
  search: Search,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  plus: Plus
}
